services:

  webserver:
    image: yiisoftware/yii2-php:8.3-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    depends_on:
      - postgres
    # закомментировать command, если не требуется обновление БД при каждом запуске
    command: >
      bash -c "refresh.sh"      
    environment:
      PHP_ENABLE_XDEBUG: 1
      XDEBUG_MODE: "coverage"
  postgres:
    image: postgres:17.0
    environment:
      POSTGRES_DB: "app-vacations"
      POSTGRES_USER: "vacation"
      POSTGRES_PASSWORD: "secret"
    ports:
      - '5432:5432'

  # Раскомментировать для запуска тестов
  # postgres-test:
  #   image: postgres:17.0
  #   environment:
  #     POSTGRES_DB: "app-vacations-test"
  #     POSTGRES_USER: "vacation"
  #     POSTGRES_PASSWORD: "secret"
  #   ports:
  #     - '5433:5432'