<?php
return [
    'user1' => [
        'username' => 'admin',
        'password' => '$2y$13$xV7iszbxVK2huPkzqV6TUePAiLgqBdjF.c0uugtYZJ07xOriVbJQ.',
        'full_name' => 'Superman',
        'position' => '',
        'email' => 'admin@admin.com',
        'org_code' => '8600',
        'org_code_select' => '',
        'created_at' => date('Y-m-d H:i:s'),
        'updated_at' => date('Y-m-d H:i:s'),
        'deleted_at' => null,
    ],
    'user2' => [
        'username' => 'user',
        'password' => '$2y$13$xV7iszbxVK2huPkzqV6TUePAiLgqBdjF.c0uugtYZJ07xOriVbJQ.',
        'full_name' => 'Jack',
        'position' => '',
        'email' => 'user@user.com',
        'org_code' => '8600',
        'org_code_select' => '',
        'created_at' => date('Y-m-d H:i:s'),
        'updated_at' => date('Y-m-d H:i:s'),
        'deleted_at' => null,
    ],
    'user3' => [
        'username' => 'test',
        'password' => '$2y$13$xV7iszbxVK2huPkzqV6TUePAiLgqBdjF.c0uugtYZJ07xOriVbJQ.',
        'full_name' => 'Polly',
        'position' => '',
        'email' => 'user2@user2.com',
        'org_code' => '8601',
        'org_code_select' => '',
        'created_at' => date('Y-m-d H:i:s'),
        'updated_at' => date('Y-m-d H:i:s'),
        'deleted_at' => date('Y-m-d H:i:s'),
    ],
];